name: Frontend CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_API_URL=http://localhost:3002 \
            -t frontend-ci .

      - name: Verify container runs
        run: docker run --rm frontend-ci node -v

  deploy:
    needs: build
    runs-on: ubuntu-latest


    steps:
      - name: Deploy frontend via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e

            # Go to frontend folder
            cd /home/ubuntu/buy-me-pencils/frontend

            # If the folder doesn't exist, clone it fresh
            if [ ! -d ".git" ]; then
              rm -rf /home/ubuntu/buy-me-pencils/frontend
              git clone https://github.com/AmirrezaAsari/buy-me-pencils-frontend.git frontend
              cd frontend
            fi

            # Make sure local branch matches remote
            git fetch --all
            git reset --hard origin/master
            git clean -fd

            # Rebuild frontend container
              docker-compose build frontend
              docker-compose down
              docker-compose up -d frontend